spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/peach_note_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: lee
    password: 1234
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: QFwhj5VKWKmk1ZXkrzoXNvLGfeif57YbcQfHCR9H++NAtj/i7kNXLLCf1XKIezbz1elbJjy9ykqtDOfw6zpyImAtVTNzmj6ODR66d5VUtcSd02HW0uIOw86oWaXbeetP5Ws9BwhsqOKHzQUR2j0WCBoBcanjsd/bbLz1J5PKNoQ=
      access-expiration: 9000000
      refresh-expiration: 2592000000
  mailing:
    activation-url: http://localhost:8088/api/v1/auth/
    activation-token-length: 6
    sender-email: peach_note@mail.com
  frontend:
    allowed-origins:
      - http://localhost:3000
    allowed-origin: http://localhost:3000

server:
  port: 8088
